- name: Deploy new container to the server
  hosts: all
  tasks:
  - name: Login to ghcr.io
    docker_login:
      url: ghcr.io
      username: '{{ username }}'
      password: '{{ password }}'

  - name: Ensure a container is running
    docker_container:
      name: bot
      state: started
      platform: linux/arm64/v8
      image: 'ghcr.io/{{ username }}/bot:latest'
      pull: true
