name: Deploy server
permissions:
  packages: write

on:
  workflow_dispatch:
  push:
    branches:
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        platforms: linux/arm64/v8
        tags: |
          ghcr.io/backroomsorg/bot:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: playbook.yaml

        directory: ./ansible

        key: ${{secrets.SSH_PRIVATE_KEY}}

        options: |
          --inventory ${{vars.BOT_HOST}},
          --extra-vars username=backroomsorg
          --extra-vars password=${{secrets.GITHUB_TOKEN}}
          --extra-vars DISCORD_TOKEN=${{secrets.BOT_TOKEN}}
          --extra-vars GUILD=${{vars.GUILD_ID}}
          --extra-vars HF_TOKEN=${{secrets.HF_TOKEN}}
          --extra-vars ERROR_WH=${{secrets.ERROR_WH}}
          --extra-vars GEMINI_TOKEN=${{secrets.GEMINI_TOKEN}}
