name: Deploy server
permissions:
  packages: write

on:
  workflow_dispatch:
  push:
    on: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        platforms: linux/arm64/v8
        tags: |
          ghcr.io/backroomsorg/bot:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: playbook.yml

        directory: ./ansible

        key: ${{secrets.SSH_PRIVATE_KEY}}

        options: |
          --inventory ${{secrets.HOST_URL}},
          --extra-vars username=${{github.repository_owner}}
          --extra-vars password=${{secrets.GITHUB_TOKEN}}

    
